name: Build and Push to GHCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      id: build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest

  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Push Docker image to GHCR
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
